security:

  providers :
    app_users:
      id: App\Security\CustomerProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: ~
      pattern: ^/
      guard:
          authenticators:
              - App\Security\CustomerAuthenticator
      logout:
        path:   app_logout
        target: app_login

  access_control:
    - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/dashboard, roles: ROLE_USER }